# Generated by Django 3.1 on 2020-09-18 14:38

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicar_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='horarios',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TimeField(), size=None),
        ),
    ]
